### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [0xnm/BTC-e-client-for-Android#6]
Would you consider attaching the `.apk` to the `releases/` so folks without GPlay have a chance to check it out? Thanks in advance!

**Comment by 0xnm** [comment]
Hello,

I've attached it to the Releases section, please check, hope this is what you was looking for.

**Comment by IzzySoft** [comment]
Sorry for my late response, somehow I've missed the notification :scream_cat:

Thanks a lot! If you wish, you can point "Google-less folk" to [this place](https://apt.izzysoft.de/fdroid/index/apk/com.QuarkLabs.BTCeClient), where they can use the F-Droid client to install your app and keep it updated. New versions are usually available within 24h after your attaching them to the resp. new release tag :smile_cat: 

PS: I've also included it with my app list for [Bitcoin & Co.](https://android.izzysoft.de/applists/category/named/finance_banking#group_1115)

**Comment by IzzySoft** [comment]
@0xnm do you still maintain this project? There was no commit for over a year. Not complaining, just wanting to know :wink:

**Comment by 0xnm** [comment]
@IzzySoft It makes no sense to develop it anymore, this cryptoexchange is pretty much dead.

**Comment by IzzySoft** [comment]
I was afraid this would be the case. I'll mark it "no longer maintained" then (unless you want me to completely remove it – which I think might be needed if it no longer works at least).
